version: '3.7'

services:

   hive-metastore:
     image: hive-metastore:3.1.3
     build:
       context: ./hive
       dockerfile: Dockerfile
     container_name: hive-metastore
     volumes:
       - ./hive/conf/hive-site.xml:/opt/apache-hive-3.1.3-bin/conf/hive-site.xml
       - ./hive/conf/hive-env.sh:/opt/apache-hive-3.1.3-bin/conf/hive-env.sh
       - ./hive/conf/core-site.xml:/opt/hadoop-3.3.2/etc/hadoop/core-site.xml
       - ./hive/conf/hdfs-site.xml:/opt/hadoop-3.3.2/etc/hadoop/hdfs-site.xml
       - ./hive/conf/mapred-site.xml:/opt/hadoop-3.3.2/etc/hadoop/mapred-site.xml
       - ./hive/conf/yarn-site.xml:/opt/hadoop-3.3.2/etc/hadoop/yarn-site.xml
     ports:
       - "9083:9083" # Hive
       - "8088:8088" # Resource Manager UI
       - "8042:8042" # Node
       - "9864:9864" # Datanode port
       - "9870:9870" # HDFS UI
     command:
       - "-c"
       - |
         echo "Starting ssh service..."
         service ssh start
         ssh-keyscan -H localhost >> ~/.ssh/known_hosts

         echo "Formating the filesystem..."
         hdfs namenode -format

         echo "Starting NameNode, DataNode, Resource Manager and Node Manager..."
         hdfs --daemon start namenode
         hdfs --daemon start datanode
         yarn --daemon start resourcemanager
         yarn --daemon start nodemanager

         echo "Creating the HDFS directories required to execute MapReduce jobs..."
         hdfs dfs -mkdir /user
         hdfs dfs -mkdir /user/$$(whoami)

         echo "Starting hive metastore"
         schematool -initSchema -dbType postgres -passWord hive -userName hive
         # tail -f /opt/hadoop-$${HADOOP_VERSION}/logs/*log
         tail -f /tmp/root/hive.log

   postgres:
     image: postgres:9.4.26
     container_name: postgres
     environment:
       POSTGRES_DB: metastore
       POSTGRES_USER: hive
       POSTGRES_PASSWORD: hive

   pgadmin:
     image: dpage/pgadmin4:6.4
     container_name: pgadmin
     environment:
       - PGADMIN_DEFAULT_EMAIL=user@domain.com
       - PGADMIN_DEFAULT_PASSWORD=root
     ports:
       - "8080:80"
